version: 1
formatters:
  standard:
    format: '[%(asctime)s - %(name)s] %(levelname)s - %(message)s'
    datefmt: '%m/%d/%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
loggers:
  general_utils:
    level: INFO
    handlers: [ console ]
    propagate: no
  CustomerChurnDataPreparation:
    level: INFO
    handlers: [ console ]
    propagate: no
  data_preparation_utils:
    level: INFO
    handlers: [ console ]
    propagate: no
  ModelTrainer:
    level: INFO
    handlers: [ console ]
    propagate: no
  model_training_utils:
    level: INFO
    handlers: [ console ]
    propagate: no